services:
  - type: web
    name: wadatrip-alerts
    env: node
    rootDir: .
    buildCommand: |
      corepack enable
      corepack prepare yarn@4.9.4 --activate
      yarn install
      yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
