services:
  - type: web
    name: wadatrip-alerts
    env: node
    rootDir: .
    buildCommand: |
      corepack enable
      corepack prepare yarn@4.9.4 --activate
      yarn install --immutable
      yarn build
    startCommand: node services/alerts/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
