services:
  - type: web
    name: wadatrip-alerts
    env: node
    rootDir: .
    buildCommand: |
      node .yarn/releases/yarn-4.9.4.cjs install --immutable
      node .yarn/releases/yarn-4.9.4.cjs workspaces focus @wadatrip/service-gateway --production
    startCommand: node .yarn/releases/yarn-4.9.4.cjs workspace @wadatrip/service-gateway start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
